[[edge_functions]]
  path = "/post/:id/og-image"
  function = "og-image"

[[edge_functions]]
  path = "/post/:id"
  function = "post-meta"

[[redirects]]
  from = "/api/*"
  to = "http://63.181.201.175/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
